<a href="https://colab.research.google.com/github/heyseeri/Introduction/blob/main/Numpy_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [ ]:
#import numpy module with alias np

import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it

import numpy as np

# Create a NumPy array from a list
arr = np.array([1, 2, 3])

print(arr)
print("Type of arr:", type(arr))

[1 2 3]
Type of arr: <class 'numpy.ndarray'>


In [ ]:
# print output
 [1 2 3]
Type of arr: <class 'numpy.ndarray'>


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [ ]:
#define a,b,c and d as instructed above

import numpy as np
# a : 0 - dimentional array
a = np.array(10)
# b : 1 - dimentional array
b = np.array([1,2,3])
# c: 2-dimensional array
c = np.array([[1, 2, 3], [4, 5, 6]])

# d: 3-dimensional array
d = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])
print("a:", a, "Shape:", a.shape)
print("b:", b, "Shape", a.shape)
print("c:", c, "Shape", c.shape)
print("d:", d, "Shape", d.shape)



a: 10 Shape: ()
b: [1 2 3] Shape ()
c: [[1 2 3]
 [4 5 6]] Shape (2, 3)
d: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] Shape (2, 2, 3)


Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [ ]:
#print dimentions of a,b, c and d

print("Dimension of a:", a.ndim)
print("Dimension of b:", b.ndim)
print("Dimension of c:", c.ndim)
print("Dimension of d:", d.ndim)



Dimension of a: 0
Dimension of b: 1
Dimension of c: 2
Dimension of d: 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d

print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)
print("Shape of d:", d.shape)




Shape of a: ()
Shape of b: (3,)
Shape of c: (2, 3)
Shape of d: (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
print("Data type of c:", c.dtype)
print("Data type of d:", d.dtype)


Data type of c: int64
Data type of d: int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [ ]:
#print type of a and b variable

print("Type of a:", type(a))
print("Type of b:", type(b))




Type of a: <class 'numpy.ndarray'>
Type of b: <class 'numpy.ndarray'>


In [ ]:
# Lets check length of array b, using len() function
# len(b)
print("Length of b:", len(b))

Length of b: 3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [ ]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array(l1)
l4 = np.array(l2)

print("List l1:", l1)
print("List l2:", l2)
print("Array l3:", l3)
print("Array l4:", l4)



List l1: [10, 20, 30]
List l2: [40, 50, 60]
Array l3: [10 20 30]
Array l4: [40 50 60]


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [ ]:
#code here as instructed above

%timeit [i * j for i, j in zip(l1, l2)]



432 ns ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [ ]:

%timeit l3 * l4



600 ns ± 9.48 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it
import numpy as np
arr = np.arange(1, 11)

print("Array using arange:", arr)



Array using arange: [ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
import numpy as np

arr = np.arange(1, 11, 2)

print("Array using arange with step 2:", arr)



Array using arange with step 2: [1 3 5 7 9]


In [ ]:
# create numpy array using eye function with 3 as passed parameter

import numpy as np
arr = np.eye(3)

print("3x3 Identity Matrix:\n", arr)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16
# x=
import numpy as np
x = np.arange(1, 17)

print("Array x:", x)


Array x: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# Reshape x with 2 rows and 8 columns

import numpy as np

x = np.arange(1, 17)
x_reshaped = x.reshape(2, 8)

print("Reshaped array (2x8):\n", x_reshaped)

Reshaped array (2x8):
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [ ]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
import numpy as np

x = np.arange(1, 17)

x_reshaped = x.reshape(2, 4, 2)

print("Reshaped array (2, 4, 2):\n", x_reshaped)



Reshaped array (2, 4, 2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
import numpy as np

x = np.arange(1, 17)

x_reshaped = x.reshape(4, -1)

print("Reshaped array (4x4):\n", x_reshaped)



Reshaped array (4x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
import numpy as np
x = np.arange(1, 17)
y = x.reshape(2, 4, -1)

print("Reshaped 3D array y:\n", y)



Reshaped 3D array y:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
# Flattening y

y_flat = y.flatten()

print("Flattened array y:\n", y_flat)


Flattened array y:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# Create an array a with all even numbers between 1 to 17
import numpy as np

a = np.arange(2, 17, 2)

print("Array of even numbers:", a)


Array of even numbers: [ 2  4  6  8 10 12 14 16]


In [ ]:
# Get third element in array a

third_element = a[2]

print("Third element of a:", third_element)

Third element of a: 6


In [ ]:
#Print 3rd, 5th, and 7th element in array a

elements = a[[2, 4, 6]]

print("3rd, 5th, and 7th elements:", elements)



3rd, 5th, and 7th elements: [ 6 10 14]


Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("2D array a:\n", a)


2D array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# print the 3rd element from the 3rd row of a
element = a[2, 2]

print("3rd element from 3rd row:", element)


3rd element from 3rd row: 9


Well done!

Now lets check indexing for 3 D array

In [26]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
import numpy as np
b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

print("3D array b:\n", b)



3D array b:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


In [29]:
# Create 1D array
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print("1D array arr:", arr)




1D array arr: [10 20 30 40 50]


In [30]:
# Slice elements from 1st to 5th element from the following array:

import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])
sliced_arr = arr[0:5]

print("Sliced elements (1st to 5th):", sliced_arr)



Sliced elements (1st to 5th): [10 20 30 40 50]


Note: The result includes the start index, but excludes the end index.



In [31]:
# Slice elements from index 5 to the end of the array:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])
sliced_arr = arr[5:]

print("Sliced elements from index 5 to end:", sliced_arr)



Sliced elements from index 5 to end: [60 70]


In [32]:
# Slice elements from the beginning to index 5 (not included):
import numpy as np


arr = np.array([10, 20, 30, 40, 50, 60, 70])

sliced_arr = arr[:5]

print("Sliced elements from start to index 5:", sliced_arr)




Sliced elements from start to index 5: [10 20 30 40 50]


**STEP**

Use the step value to determine the step of the slicing:

In [33]:
# Print every other element from index 1 to index 7:

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
sliced_arr = arr[1:8:2]

print("Every other element from index 1 to 7:", sliced_arr)


Every other element from index 1 to 7: [20 40 60 80]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [34]:
# Return every other element from the entire array arr:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

every_other = arr[::2]

print("Every other element from the entire array:", every_other)



Every other element from the entire array: [10 30 50 70 90]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [36]:
# Print array a

#Array a: [ 2  4  6  8 10 12 14 16]

In [37]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

import numpy as np

a = np.array([2, 4, 6, 8, 10, 12, 14, 16])
sub_arr = a[2:]       # [6, 8, 10, 12, 14, 16]

result = sub_arr[1:5]

print("Sliced elements:", result)

Sliced elements: [ 8 10 12 14]


In [38]:
# In array 'a' print index 2 from all the elements :
import numpy as np

a = np.array([[2, 4, 6, 8],
              [10, 12, 14, 16],
              [18, 20, 22, 24]])



In [39]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:

import numpy as np

a = np.array([[2, 4, 6, 8],
              [10, 12, 14, 16],
              [18, 20, 22, 24]])
result = a[:, 1:]

print("Sliced 2D array:\n", result)


Sliced 2D array:
 [[ 4  6  8]
 [12 14 16]
 [20 22 24]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [43]:
# x1
import numpy as np
x1 = np.array([1, 2, 3, 4, 5])
print("x1:", x1)




x1: [1 2 3 4 5]


In [44]:
# Assign x2 to be the same as x1
x2 = x1

print("x2:", x2)


x2: [1 2 3 4 5]


In [45]:
#print x1 and x2

print("x1:", x1)
print("x2:", x2)



x1: [1 2 3 4 5]
x2: [1 2 3 4 5]


Ok now you have seen that both of them are same

In [46]:
# change 1st element of x2 as 10

# Change 1st element of x2 to 10
x2[0] = 10

print("x2 after change:", x2)
print("x1 after change:", x1)



x2 after change: [10  2  3  4  5]
x1 after change: [10  2  3  4  5]


In [47]:
#Again print x1 and x2

print("x1:", x1)
print("x2:", x2)


x1: [10  2  3  4  5]
x2: [10  2  3  4  5]


In [48]:
# Check memory share between x1 and x2

import numpy as np

# Check if x1 and x2 share memory
memory_shared = np.shares_memory(x1, x2)

print("Do x1 and x2 share memory?", memory_shared)

Do x1 and x2 share memory? True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [49]:
# Create a view of x1 and store it in x3.

x3 = x1.view()

print("x3 (view of x1):", x3)


x3 (view of x1): [10  2  3  4  5]


In [50]:
# Again check memory share between x1 and x3
import numpy as np

memory_shared = np.shares_memory(x1, x3)

print("Do x1 and x3 share memory?", memory_shared)

Do x1 and x3 share memory? True


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [51]:
#Change 1st element of x3=100

x3[0] = 100

print("x3 after change:", x3)
print("x1 after change:", x1)

x3 after change: [100   2   3   4   5]
x1 after change: [100   2   3   4   5]


In [52]:
#print x1 and x3 to check if changes reflected in both

print("x1:", x1)
print("x3:", x3)


x1: [100   2   3   4   5]
x3: [100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [53]:
# Now create an array x4 which is copy of x1

x4 = x1.copy()

print("x4 (copy of x1):", x4)



x4 (copy of x1): [100   2   3   4   5]


In [54]:
# Change the last element of x4 as 900

x4[-1] = 900

print("x4 after change:", x4)
print("x1 remains unchanged:", x1)



x4 after change: [100   2   3   4 900]
x1 remains unchanged: [100   2   3   4   5]


In [55]:
# print both x1 and x4 to check if changes reflected in both

print("x1:", x1)
print("x4:", x4)



x1: [100   2   3   4   5]
x4: [100   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [56]:
#Check memory share between x1 and x4
import numpy as np

memory_shared = np.shares_memory(x1, x4)

print("Do x1 and x4 share memory?", memory_shared)



Do x1 and x4 share memory? False


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [57]:
# stack x1 and x4 along columns.
import numpy as np
stacked = np.column_stack((x1, x4))

print("Stacked along columns:\n", stacked)

Stacked along columns:
 [[100 100]
 [  2   2]
 [  3   3]
 [  4   4]
 [  5 900]]


In [58]:
#stack x1 and x4 along rows

import numpy as np

stacked_rows = np.vstack((x1, x4))

print("Stacked along rows:\n", stacked_rows)

Stacked along rows:
 [[100   2   3   4   5]
 [100   2   3   4 900]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [59]:
import numpy as np


arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])


joined_rows = np.concatenate((arr1, arr2), axis=0)

print("Joined along rows:\n", joined_rows)




Joined along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [60]:
##join arr1 and arr2 along columns using concatenate() function
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

joined_columns = np.concatenate((arr1, arr2), axis=1)

print("Joined along columns:\n", joined_columns)


Joined along columns:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [61]:
# append arr2 to arr1
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

appended = np.append(arr1, arr2, axis=0)

print("Appended array along rows:\n", appended)


Appended array along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Lets use insert() function which Inserts values into array before specified index value

In [62]:
# Inserts values into array x1 before index 4 with elements of x4

import numpy as np

x1_modified = np.insert(x1, 4, x4)

print("x1 after inserting x4 before index 4:\n", x1_modified)

x1 after inserting x4 before index 4:
 [100   2   3   4 100   2   3   4 900   5]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [63]:
# delete 2nd element from array x2
import numpy as np

x2_modified = np.delete(x2, 1)

print("x2 after deleting 2nd element:", x2_modified)



x2 after deleting 2nd element: [100   3   4   5]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!

In [41]:
# Define x1
import numpy as np
x1 = np.array([1, 2, 3, 4, 5])
print("x1:", x1)

x1: [1 2 3 4 5]
